name: astrogame_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  logger:

  # Used for dependency injection
  get_it: 
  injectable:

  # MVVM pattern
  stacked:
  stacked_themes:
  stacked_services:

  # Used for easier Api writing
  retrofit:
  dio: ^3.0.10

  # Used to get the devices information like manufacturer, version, or if it a physical device
  device_info: 

  # Used to send events between ViewModels
  event_bus:

  google_fonts:
  expandable:

  flutter_guid:

  flutter_svg:
      
  desktop_window:
  bitsdojo_window:

  flutter_inner_drawer:
  responsive_builder:

  google_nav_bar:
  badges: ^1.2.0

  tuple:

  enhanced_future_builder:

  intl:

  synchronized:

  duration:

  signalr_core:

  flutter_memory_cache:

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator:
  build_runner:

  # Used to generate the Apis
  retrofit_generator:

  # This dev dependency needs to be added to automatically generate json objects
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: TTFirsNeue
      fonts:
        - asset: assets/fonts/TTFirsNeue3.ttf
        - asset: assets/fonts/TTFirsNeue_Medium.ttf
          weight: 500
