// <auto-generated />
using System;
using AstroGame.Api.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AstroGame.Api.Migrations
{
    [DbContext(typeof(AstroGameDataContext))]
    partial class AstroGameDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.Prefab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Offset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Prefab");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.BaseTypes.StellarObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<double?>("AverageDistanceToCenter")
                        .HasColumnType("float");

                    b.Property<int>("AverageTemperature")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("RotationSpeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("StellarObject");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.BaseTypes.StellarSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("MultiObjectSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StellarSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MultiObjectSystemId");

                    b.HasIndex("ParentId");

                    b.HasIndex("StellarSystemId");

                    b.ToTable("StellarSystem");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.CloudsPrefab", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Prefabs.Prefab");

                    b.ToTable("CloudsPrefabs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-1111-0000-0000-000000000001"),
                            Name = "Clouds_1",
                            Offset = "(0.0, 0.0, -1.0)",
                            Rotation = "(-1.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)"
                        });
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.MoonPrefab", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Prefabs.Prefab");

                    b.ToTable("MoonPrefabs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-2222-0000-0000-000000000001"),
                            Name = "Moon_1",
                            Offset = "(0.0, 0.0, -1.0)",
                            Rotation = "(-1.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)"
                        },
                        new
                        {
                            Id = new Guid("00000000-2222-0000-0000-000000000002"),
                            Name = "Moon_2",
                            Offset = "(0.0, 0.0, -1.0)",
                            Rotation = "(-1.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)"
                        },
                        new
                        {
                            Id = new Guid("00000000-2222-0000-0000-000000000003"),
                            Name = "Moon_3",
                            Offset = "(0.0, 0.0, -1.0)",
                            Rotation = "(-1.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)"
                        });
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.PlanetAtmospherePrefab", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Prefabs.Prefab");

                    b.Property<string>("PlanetTypes")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PlanetAtmospherePrefabs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-3333-0000-0000-000000000001"),
                            Name = "PlanetAtmosphere_1",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetTypes = "Volcano;Desert"
                        },
                        new
                        {
                            Id = new Guid("00000000-3333-0000-0000-000000000002"),
                            Name = "PlanetAtmosphere_2",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetTypes = "Volcano;Desert"
                        },
                        new
                        {
                            Id = new Guid("00000000-3333-0000-0000-000000000003"),
                            Name = "PlanetAtmosphere_3",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetTypes = "Continental;Rock"
                        },
                        new
                        {
                            Id = new Guid("00000000-3333-0000-0000-000000000004"),
                            Name = "PlanetAtmosphere_4",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetTypes = "Gaia;Gas"
                        },
                        new
                        {
                            Id = new Guid("00000000-3333-0000-0000-000000000005"),
                            Name = "PlanetAtmosphere_5",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetTypes = "Ocean;Ice"
                        });
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.PlanetPrefab", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Prefabs.Prefab");

                    b.Property<int>("PlanetType")
                        .HasColumnType("int");

                    b.ToTable("PlanetPrefabs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Planet_Volcano_1",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Planet_Volcano_2",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Planet_Volcano_3",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Planet_Desert_1",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Planet_Desert_2",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Planet_Desert_3",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Planet_Continental_1",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "Planet_Continental_2",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Name = "Planet_Continental_3",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Name = "Planet_Rock_1",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 4
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Name = "Planet_Rock_2",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 4
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "Planet_Rock_3",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 4
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Name = "Planet_Gaia_1",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 7
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Name = "Planet_Gaia_2",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 7
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Name = "Planet_Gaia_3",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 7
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Name = "Planet_Gas_1",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 5
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Name = "Planet_Gas_2",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 5
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Name = "Planet_Gas_3",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 5
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Name = "Planet_Ocean_1",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 3
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Name = "Planet_Ocean_2",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 3
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Name = "Planet_Ocean_3",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 3
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            Name = "Planet_Ice_1",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 6
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            Name = "Planet_Ice_2",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 6
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            Name = "Planet_Ice_3",
                            Offset = "(0.0, 0.0, 0.0)",
                            Rotation = "(0.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            PlanetType = 6
                        });
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.RingsPrefab", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Prefabs.Prefab");

                    b.ToTable("RingsPrefabs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-4444-0000-0000-000000000001"),
                            Name = "Rings_1",
                            Offset = "(0.0, 0.0, -1.0)",
                            Rotation = "(-1.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)"
                        });
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.StarPrefab", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Prefabs.Prefab");

                    b.Property<int>("StarType")
                        .HasColumnType("int");

                    b.ToTable("StarPrefabs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-5555-0000-0000-000000000001"),
                            Name = "Test_Prefab",
                            Offset = "(0.0, 0.0, -1.0)",
                            Rotation = "(-1.0, 0.0, 0.0)",
                            Scale = "(0.0, 0.0, 0.0)",
                            StarType = 0
                        });
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarObjects.Moon", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Stellar.BaseTypes.StellarObject");

                    b.Property<double>("AxialTilt")
                        .HasColumnType("float");

                    b.Property<Guid>("PrefabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RingPrefabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RingsPrefabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Scale")
                        .HasColumnType("float");

                    b.HasIndex("PrefabId");

                    b.HasIndex("RingsPrefabId");

                    b.ToTable("Moons");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarObjects.Planet", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Stellar.BaseTypes.StellarObject");

                    b.Property<Guid?>("AtmospherePrefabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AxialTilt")
                        .HasColumnType("float");

                    b.Property<Guid?>("CloudsPrefabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlanetType")
                        .HasColumnType("int");

                    b.Property<Guid>("PrefabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RingPrefabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Scale")
                        .HasColumnType("float");

                    b.HasIndex("AtmospherePrefabId");

                    b.HasIndex("CloudsPrefabId");

                    b.HasIndex("PrefabId");

                    b.HasIndex("RingPrefabId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarObjects.Star", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Stellar.BaseTypes.StellarObject");

                    b.Property<double>("AxialTilt")
                        .HasColumnType("float");

                    b.Property<Guid>("PrefabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Scale")
                        .HasColumnType("float");

                    b.Property<int>("StarType")
                        .HasColumnType("int");

                    b.HasIndex("PrefabId");

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarSystems.MultiObjectSystem", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Stellar.BaseTypes.StellarSystem");

                    b.ToTable("MultiObjectSystems");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarSystems.SingleObjectSystem", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Stellar.BaseTypes.StellarSystem");

                    b.Property<Guid>("CenterObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CenterObjectId")
                        .IsUnique()
                        .HasFilter("[CenterObjectId] IS NOT NULL");

                    b.ToTable("SingleObjectSystems");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarSystems.SolarSystem", b =>
                {
                    b.HasBaseType("AstroGame.Shared.Models.Stellar.StellarSystems.MultiObjectSystem");

                    b.ToTable("SolarSystems");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.BaseTypes.StellarSystem", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Stellar.StellarSystems.MultiObjectSystem", null)
                        .WithMany("CenterSystems")
                        .HasForeignKey("MultiObjectSystemId");

                    b.HasOne("AstroGame.Shared.Models.Stellar.BaseTypes.StellarSystem", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("AstroGame.Shared.Models.Stellar.BaseTypes.StellarSystem", null)
                        .WithMany("Satellites")
                        .HasForeignKey("StellarSystemId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.CloudsPrefab", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Prefabs.Prefab", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Prefabs.CloudsPrefab", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.MoonPrefab", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Prefabs.Prefab", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Prefabs.MoonPrefab", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.PlanetAtmospherePrefab", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Prefabs.Prefab", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Prefabs.PlanetAtmospherePrefab", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.PlanetPrefab", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Prefabs.Prefab", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Prefabs.PlanetPrefab", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.RingsPrefab", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Prefabs.Prefab", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Prefabs.RingsPrefab", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Prefabs.StarPrefab", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Prefabs.Prefab", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Prefabs.StarPrefab", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarObjects.Moon", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Stellar.BaseTypes.StellarObject", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Stellar.StellarObjects.Moon", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("AstroGame.Shared.Models.Prefabs.MoonPrefab", "Prefab")
                        .WithMany()
                        .HasForeignKey("PrefabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroGame.Shared.Models.Prefabs.RingsPrefab", "RingsPrefab")
                        .WithMany()
                        .HasForeignKey("RingsPrefabId");

                    b.Navigation("Prefab");

                    b.Navigation("RingsPrefab");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarObjects.Planet", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Prefabs.PlanetAtmospherePrefab", "AtmospherePrefab")
                        .WithMany()
                        .HasForeignKey("AtmospherePrefabId");

                    b.HasOne("AstroGame.Shared.Models.Prefabs.CloudsPrefab", "CloudsPrefab")
                        .WithMany()
                        .HasForeignKey("CloudsPrefabId");

                    b.HasOne("AstroGame.Shared.Models.Stellar.BaseTypes.StellarObject", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Stellar.StellarObjects.Planet", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("AstroGame.Shared.Models.Prefabs.PlanetPrefab", "Prefab")
                        .WithMany()
                        .HasForeignKey("PrefabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroGame.Shared.Models.Prefabs.RingsPrefab", "RingsPrefab")
                        .WithMany()
                        .HasForeignKey("RingPrefabId");

                    b.Navigation("AtmospherePrefab");

                    b.Navigation("CloudsPrefab");

                    b.Navigation("Prefab");

                    b.Navigation("RingsPrefab");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarObjects.Star", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Stellar.BaseTypes.StellarObject", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Stellar.StellarObjects.Star", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("AstroGame.Shared.Models.Prefabs.StarPrefab", "Prefab")
                        .WithMany()
                        .HasForeignKey("PrefabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prefab");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarSystems.MultiObjectSystem", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Stellar.BaseTypes.StellarSystem", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Stellar.StellarSystems.MultiObjectSystem", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarSystems.SingleObjectSystem", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Stellar.BaseTypes.StellarObject", "CenterObject")
                        .WithOne("ParentSystem")
                        .HasForeignKey("AstroGame.Shared.Models.Stellar.StellarSystems.SingleObjectSystem", "CenterObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstroGame.Shared.Models.Stellar.BaseTypes.StellarSystem", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Stellar.StellarSystems.SingleObjectSystem", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CenterObject");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarSystems.SolarSystem", b =>
                {
                    b.HasOne("AstroGame.Shared.Models.Stellar.StellarSystems.MultiObjectSystem", null)
                        .WithOne()
                        .HasForeignKey("AstroGame.Shared.Models.Stellar.StellarSystems.SolarSystem", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.BaseTypes.StellarObject", b =>
                {
                    b.Navigation("ParentSystem");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.BaseTypes.StellarSystem", b =>
                {
                    b.Navigation("Satellites");
                });

            modelBuilder.Entity("AstroGame.Shared.Models.Stellar.StellarSystems.MultiObjectSystem", b =>
                {
                    b.Navigation("CenterSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
